/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=.wrangler/types/wrangler.jsonc --env-file=wrangler.types.env --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings types/cloudflare-bindings.d.ts` (hash: c840d1af89e391da188b0aeded8b6895)
interface __BaseEnv_CloudflareBindings {
	CACHE_KV: KVNamespace;
	DB: D1Database;
	SESSION_SECRET: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SESSION_SECRET">> {}
}
