import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const projectRoot = process.cwd()

function source(path: string): string {
  return readFileSync(join(projectRoot, path), 'utf8')
}

describe('public SSR request boundaries', () => {
  it('keeps site and search configuration under one owner each', () => {
    expect(source('app.vue')).toContain('usePublicSiteConfig()')
    expect(source('layouts/default.vue')).not.toContain('usePublicSiteConfig()')
    expect(source('composables/useSiteConfig.ts')).not.toMatch(
      /export function useSeoContext\(\)[\s\S]*usePublicSiteConfig\(\)/
    )

    expect(source('layouts/default.vue')).toContain('useSearchConfig({ server: false })')
    expect(source('pages/search.vue')).toContain('useSearchConfigState()')
    expect(source('pages/search.vue')).not.toContain('useSearchConfig()')
  })

  it('preserves SSR request context and cancellation in the shared public loader', () => {
    const loader = source('composables/useStaleFirstPublicResource.ts')
    expect(loader).toContain('import.meta.server ? useRequestFetch() : $fetch')
    expect(loader).toContain("dedupe: 'defer'")
    expect(loader).toContain('fetchResource(signal)')
  })

  it('marks required public SSR resources unavailable instead of returning empty HTTP 200 pages', () => {
    for (const file of [
      'pages/index.vue',
      'pages/categories/index.vue',
      'pages/categories/[slug].vue',
      'pages/tags/index.vue',
      'pages/tags/[slug].vue',
      'pages/archive.vue',
      'pages/about.vue',
      'pages/posts/[slug].vue'
    ]) {
      expect(source(file), file).toMatch(/setResponseStatus\(event, 503/)
    }
    expect(source('pages/about.vue')).toContain('isPublicNotFoundError(error.value)')
    expect(source('pages/about.vue')).toContain('About page temporarily unavailable')
  })

  it('uses generated Cloudflare bindings and one H3 context augmentation', () => {
    expect(source('types/cloudflare-bindings.d.ts')).toContain('Generated by Wrangler')
    expect(source('types/h3.d.ts')).toContain('Partial<CloudflareBindings>')

    const serverFiles = [
      'server/database/client.ts',
      'server/providers/cache/cache-provider-factory.ts',
      'server/providers/comment-moderation/comment-moderation-provider-factory.ts',
      'server/providers/comment-protection/comment-protection-provider-factory.ts',
      'server/providers/comment-replica/comment-replica-provider-factory.ts',
      'server/providers/storage/storage-provider-factory.ts',
      'server/services/admin-post-service-factory.ts',
      'server/services/analytics-report-service-factory.ts',
      'server/services/integration-service-factory.ts',
      'server/services/search-sync-retry-service-factory.ts'
    ]
    for (const file of serverFiles) {
      expect(source(file), file).not.toContain('interface CloudflareEventContext')
    }
  })
})
